'use client'
import { useCallback, useEffect, useState } from 'react'
import styles from './dashboard.module.css'
type GlyphSnapshot={verifiedAt:string;studioUrl:string;live?:boolean;connectionError?:string;characters:{id:string;name:string;primary_asset_id:string|null;rights_status:string;voice_status:string|null;portrait_url?:string|null;approved_reference_count?:number;blockers?:string[]}[]}
type Candidate={key:string;kind:string;subject:string;path:string;sha256:string;source?:string;reviewNotes?:string;approved:{url:string;version:string}|null}
export default function ReferencePanel({onChanged}:{onChanged:()=>void}) {
 const [glyph,setGlyph]=useState<GlyphSnapshot|null>(null)
 const [items,setItems]=useState<Candidate[]>([]),[selected,setSelected]=useState<Candidate|null>(null),[identity,setIdentity]=useState(false),[layout,setLayout]=useState(false),[emptyRoom,setEmptyRoom]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('')
 const load=useCallback(async()=>{const r=await fetch('/api/content/references',{cache:'no-store'}),b=await r.json();if(!r.ok)throw Error(b.error);setItems(b.candidates);setGlyph(b.glyphCharacters)},[])
 useEffect(()=>{void load().catch(e=>setMessage(e.message))},[load])
 async function approve(){if(!selected)return;setBusy(true);try{const r=await fetch('/api/content/references',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({key:selected.key,expectedSha:selected.sha256,confirmIdentity:identity,confirmLayout:layout,confirmEmptyRoom:emptyRoom})}),b=await r.json();if(!r.ok)throw Error(b.error);setSelected(null);setMessage('Master image approved and registered. Future work can reuse this version.');await load();onChanged()}catch(e){setMessage(e instanceof Error?e.message:'Unable to approve')}finally{setBusy(false)}}
 return <section><h2>Master references</h2><p>Room design proposals and existing venue images are review candidates. Approve only if they match your intended venue or the exact character. Approval registers this image version for reuse; it does not approve every future render.</p><p>Room proposals preserve the existing design pack; dimensions and property geometry remain provisional. Characters use the GLYPH registry below. Character video generation remains held until its production path and episode checks are connected.</p>{message && <p role="status">{message}</p>}
 {selected ? <div className={styles.card} style={{padding:24}}><button className={styles.secondary} disabled={busy} onClick={()=>setSelected(null)}>← Back to references</button><h3>{selected.subject.replaceAll('_',' ')} · {selected.kind}</h3><img src={selected.path} alt={`${selected.subject} reference candidate`} style={{height:'auto',maxHeight:'65vh',objectFit:'contain'}}/><p>{selected.source || "Existing website image"}</p><p>{selected.reviewNotes}</p><p>Inspect the full image. If it is inaccurate, leave it unapproved.</p><label style={{display:'block',padding:12}}><input type="checkbox" checked={identity} onChange={e=>setIdentity(e.target.checked)}/> This is the exact intended room or character identity.</label><label style={{display:'block',padding:12}}><input type="checkbox" checked={layout} onChange={e=>setLayout(e.target.checked)}/> I checked layout/details, branding, appearance and exclusions; this image is suitable as a master.</label><>{selected.kind==='venue' && <label style={{display:'block',padding:12}}><input type="checkbox" checked={emptyRoom} onChange={e=>setEmptyRoom(e.target.checked)}/> This is an empty-room keyframe with no people. Existing scene images with guests are not suitable.</label>}</><button className={styles.approve} disabled={busy || !identity || !layout || (selected.kind==='venue' && !emptyRoom)} onClick={approve}>✓ Approve this master image</button></div>
 : <div className={styles.cards}>{items.map(item=><article key={item.key} className={styles.card}><img src={item.approved?.url || item.path} alt={`${item.subject} reference`} loading="lazy"/><div className={styles.cardBody}><h3>{item.subject.replaceAll('_',' ')} · {item.kind}</h3><p>{item.source || 'Existing website image'}</p><p>{item.reviewNotes}</p><p>{item.approved?'Approved master registered':'Candidate — approval required'}</p>{item.approved?<p>Version: {item.approved.version}</p>:<button className={styles.primary} onClick={()=>{setSelected(item);setIdentity(false);setLayout(false);setEmptyRoom(false);setMessage('')}}>Inspect and approve reference →</button>}</div></article>)}</div>}{glyph && <div style={{marginTop:32}}><h2>GLYPH character masters · {glyph.characters.length}</h2><p>{glyph.live?'Live GLYPH registry':'Last verified GLYPH snapshot'} · {new Date(glyph.verifiedAt).toLocaleString()}. {glyph.live?'Current portraits, image approvals and voice status are read directly from GLYPH. Refresh to check for changes.':glyph.connectionError || 'Live connection unavailable.'} Reference approval alone does not authorize a generated episode.</p><p>Chef V is the tentative first Kitchen guest. Each voice remains governed by its GLYPH record.</p><button className={styles.secondary} onClick={()=>void load().catch(e=>setMessage(e.message))}>↻ Refresh canonical records</button><div className={styles.cards}>{glyph.characters.map(c=><article key={c.id} className={styles.card}>{c.portrait_url && <a href={c.portrait_url} target="_blank" rel="noopener noreferrer" title="Inspect the approved primary portrait"><img src={c.portrait_url} alt={`${c.name} approved canonical portrait`} loading="lazy" style={{objectFit:"contain",height:280}}/></a>}<div className={styles.cardBody}><h3>{c.name}</h3><p>Primary image: {c.rights_status}{c.approved_reference_count!==undefined?` · ${c.approved_reference_count} approved references`:""}</p><p>Voice: {c.voice_status || "Not configured"}</p>{c.blockers && c.blockers.length>0 && <p>Production checks: {c.blockers.map(b=>b.replaceAll("_"," ")).join("; ")}</p>}<details><summary>Canonical asset details</summary><p>Registry ID: {c.id}</p><p>Primary asset: {c.primary_asset_id}</p></details><a className={styles.primary} href={glyph.studioUrl} target="_blank" rel="noopener noreferrer">Open GLYPH → Characters → {c.name}</a></div></article>)}</div></div>}</section>
}
