const fs=require('fs'),ts=require('typescript'),vm=require('vm'),assert=require('node:assert/strict');
const compile=p=>ts.transpileModule(fs.readFileSync(p,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText;
const id='11111111-1111-4111-8111-111111111111',jobId='22222222-2222-4222-8222-222222222222';
const item={id,site_category:'gallery',source_job_id:jobId,media_url:`/api/content/media/items/${id}`,approved_by:'owner',approved_at:'now',copy_final:'Approved overview',status:'scheduled',scheduled_at:'2026-01-01T00:00:00Z'};
const job={id:jobId,room:'gallery',status:'approved',qa_approved_by:'owner',qa_approved_at:'now',policy_version:'2026-10-07',output_url:jobId+'.mp4',canonical_asset_id:'reference'};
const asset={id:'reference',kind:'venue',subject:'gallery',active:true,approved_by:'owner',approved_at:'now',version:'1',url:'https://example.com/ref.png',sha256:'a'.repeat(64)};
const db={from(table){let filters=[];const q={select(){return q},eq(k,v){filters.push(r=>r[k]===v);return q},in(k,v){filters.push(r=>v.includes(r[k]));return q},maybeSingle:async()=>{const row=table==='content_items'?item:table==='cs_content_jobs'?job:asset;return {data:filters.every(f=>f(row))?row:null,error:null}}};return q},storage:{from(){return {createSignedUrl:async()=>({data:{signedUrl:'https://private.example/token'}})}}}};
const policy={exports:{},Date,Intl,URL};vm.runInNewContext(compile('lib/content/policy.ts'),policy);
const helper={exports:{},require:n=>n.endsWith('/policy')?policy.exports:{createAdminClient:()=>db}};vm.runInNewContext(compile('lib/content/approved-media.ts'),helper);
let allowDownload=false;
class NextResponse extends Response {}
const route={exports:{},Date,Number,Headers,AbortSignal,require(n){if(n==='next/server')return {NextResponse};if(n.endsWith('/approved-media'))return helper.exports;if(n.endsWith('/media-access'))return {canDownloadContentMedia:async()=>allowDownload};return {createAdminClient:()=>db}},fetch:async(url,opts)=>new Response('clip',{status:opts.headers.Range?206:200})};vm.runInNewContext(compile('app/api/content/media/items/[id]/route.ts'),route);
const req=(download=false,range=null)=>({nextUrl:{searchParams:new URLSearchParams(download?'download=1':'')},headers:{get:()=>range}});
(async()=>{assert.ok(await helper.exports.approvedMediaJob(item));job.room='bar';assert.equal(await helper.exports.approvedMediaJob(item),null);job.room='gallery';job.qa_approved_at=null;assert.equal(await helper.exports.approvedMediaJob(item),null);job.qa_approved_at='now';asset.active=false;assert.equal(await helper.exports.approvedMediaJob(item),null);asset.active=true;job.output_url='../secret.mp4';assert.equal(await helper.exports.approvedMediaJob(item),null);job.output_url=jobId+'.mp4';assert.equal(await helper.exports.approvedMediaJob({...item,media_url:'https://evil.example/clip'}),null);item.scheduled_at='2099-01-01T00:00:00Z';assert.equal((await route.exports.GET(req(),{params:{id}})).status,404);item.scheduled_at='bad-date';assert.equal((await route.exports.GET(req(),{params:{id}})).status,404);item.scheduled_at='2026-01-01T00:00:00Z';assert.equal((await route.exports.GET(req(true),{params:{id}})).status,403);const playback=await route.exports.GET(req(false,'bytes=0-3'),{params:{id}});assert.equal(playback.status,206);assert.equal(playback.headers.get('location'),null);assert.match(playback.headers.get('content-disposition'),/^inline/);allowDownload=true;assert.match((await route.exports.GET(req(true),{params:{id}})).headers.get('content-disposition'),/^attachment/);item.approved_by=null;assert.equal((await route.exports.GET(req(),{params:{id}})).status,404);console.log('PASS: matching QA/canon required; future and invalid dates withheld; private range playback and restricted downloads')})().catch(e=>{console.error(e);process.exitCode=1});
