const fs=require('fs'),ts=require('typescript'),vm=require('vm'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const compile=p=>ts.transpileModule(fs.readFileSync(p,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText;
const env={CS_SOCIAL_ENCRYPTION_KEY:crypto.randomBytes(32).toString('base64'),CS_METRICOOL_OAUTH_CLIENT_ID:'test-client'};
const oauth={exports:{},Buffer,URL,URLSearchParams,Date,AbortSignal,process:{env},require:()=>crypto};vm.runInNewContext(compile('lib/content/metricool-oauth.ts'),oauth);
let authorized=false,stored=null,tokenCalls=0;
class NextResponse {constructor(body,status){this.body=body;this.status=status;this.headers=new Headers();this.savedCookies={};this.cookies={set:(name,value)=>{this.savedCookies[name]=value}}}static json(body,init){return new NextResponse(body,init?.status||200)}static redirect(url){const r=new NextResponse(null,307);r.headers.set('location',url);return r}}
const deps=n=>n==='next/server'?{NextResponse}:n.endsWith('/auth')?{isContentAdmin:async()=>authorized}:n.endsWith('/server')?{createClient:()=>({auth:{getUser:async()=>({data:{user:{id:'owner'}}})}})}:n.endsWith('/admin')?{createAdminClient:()=>({from:()=>({upsert:async row=>{stored=row;return {error:null}}})})}:n.endsWith('/metricool-mcp')?{verifyMetricoolConnection:async()=>({brandId:5373515,userId:4174093,label:'Tru Skool'})}:n.endsWith('/metricool-oauth')?{...oauth.exports,providerJson:async(path,params)=>{tokenCalls++;assert.equal(params.get('redirect_uri'),oauth.exports.CALLBACK);return {access_token:'test-access',refresh_token:'test-refresh',token_type:'Bearer'}}}:null;
const load=path=>{const c={exports:{},Headers,Date,URLSearchParams,process:{env},require:deps};vm.runInNewContext(compile(path),c);return c.exports};
const connect=load('app/api/content/social/connect/route.ts'),callback=load('app/api/content/social/callback/route.ts');
const req=(origin='https://www.cafe-sativa.com')=>({headers:{get:()=>origin},nextUrl:{origin}});
(async()=>{assert.equal((await connect.POST(req())).status,401);authorized=true;assert.equal((await connect.POST(req('https://evil.example'))).status,403);const start=await connect.POST(req());assert.equal(start.status,200);const cookie=start.savedCookies[oauth.exports.COOKIE],url=new URL(start.body.url);const finish=state=>({nextUrl:{searchParams:new URLSearchParams({code:'test-code',state})},cookies:{get:()=>({value:cookie})}});await callback.GET(finish('wrong-state'));assert.equal(tokenCalls,0);assert.equal(stored,null);const result=await callback.GET(finish(url.searchParams.get('state')));assert.match(result.headers.get('location'),/metricool=connected$/);assert.equal(stored.dispatch_enabled,false);assert.equal(stored.owner_id,'owner');assert.equal(oauth.exports.unseal(stored.credential_ciphertext,'credentials').refresh_token,'test-refresh');assert.ok(!JSON.stringify(result).includes('test-access'));assert.equal(result.savedCookies[oauth.exports.COOKIE],'');console.log('PASS: admin/origin gates, invalid state makes no token call, valid callback encrypts credentials and leaves dispatch disabled')})().catch(e=>{console.error(e);process.exitCode=1});
